version: "3.8"

services:
  pastechs-website:
    image: ghcr.io/nanthawat2540/pastechs-website:latest
    container_name: pastechs-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: /opt/pastechs/.env
    volumes:
      - /opt/pastechs/uploads:/app/public/uploads
    networks:
      - proxy-net

networks:
  proxy-net:
    external: true
